vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|19 Sep 2014 21:29:30 -0000
vti_extenderversion:SR|12.0.0.0
vti_author:SR|Justin-PC\\Justin
vti_modifiedby:SR|Justin-PC\\Justin
vti_timecreated:TR|19 Sep 2014 21:29:30 -0000
vti_cacheddtm:TX|19 Sep 2014 21:29:30 -0000
vti_filesize:IR|18277
vti_cachedbodystyle:SR|<body class="off">
vti_cachedlinkinfo:VX|X|css/bootstrap.min.css X|css/font-awesome.min.css X|css/prettyPhoto.css X|css/flexslider.css X|css/icons.css X|layerslider/css/layerslider.css X|css/main.css X|css/bule.css X|css/animate.css X|css/yummi-loader.css X|js/modernizr-2.6.2-respond-1.1.0.min.js X|js/jquery-1.10.2.min.js X|js/jquery-ui.js X|layerslider/jQuery/jquery-easing-1.3.js X|layerslider/jQuery/jquery-transit-modified.js X|layerslider/js/layerslider.transitions.js X|layerslider/js/layerslider.kreaturamedia.jquery.js X|http://ajax.googleapis.com/ajax/libs/jquery/x.x.x/jquery.min.js X|css/font-awesome-ie7.min.css H|https://www.facebook.com/pages/Access-To-A-Better-Tomorrow/7574851076461966 K|thank_you.php S|img/logo.png S|img/logo.png H|resources.html S|icon_1.png H|resources.html S|icon_2.png H|resources.html S|icon_3.png H|resources.html S|icon_4.png H|resources.html S|icon_5.png H|resources.html S|icon_6.png H|resources.html S|icon_7.png H|index.html H|about.html H|resources.html H|events.html H|news.html H|donate.html H|contactus.html H|mailto:justinp@a-bt.org H|https://www.facebook.com/pages/Access-To-A-Better-Tomorrow/7574851076461966 S|img/s6.png S|img/s4.png S|img/s1.png S|img/s2.png S|img/s3.png S|img/s5.png S|img/s7.png S|img/s8.png S|img/s9.png S|img/s10.png S|img/s11.png S|img/s12.png S|img/s13.png S|img/s14.png S|img/s15.png S|img/s16.png A|https://www.paypal.com/cgi-bin/webscr H|https://www.gagivesday.org/c/GGD/Search S|https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif S|https://www.paypalobjects.com/en_US/i/scr/pixel.gif H|https://www.facebook.com/pages/Access-To-A-Better-Tomorrow/7574851076461966 S|js/jquery.queryloader2.js S|js/bootstrap.min.js S|js/twitter-bootstrap-hover-dropdown.min.js S|js/jquery.carouFredSel-6.2.1.js S|js/jquery.touchSwipe.min.js S|js/jquery.prettyPhoto.js S|js/jquery.flexslider-min.js S|js/waypoints.min.js S|js/jquery.stellar.min.js S|js/masonry.pkgd.min.js S|js/SmoothScroll.js S|js/main.js S|js/styleswitcher.js
vti_cachedsvcrellinks:VX|FXUS|css/bootstrap.min.css FXUS|css/font-awesome.min.css FXUS|css/prettyPhoto.css FXUS|css/flexslider.css FXUS|css/icons.css FXUS|layerslider/css/layerslider.css FXUS|css/main.css FXUS|css/bule.css FXUS|css/animate.css FXUS|css/yummi-loader.css FXUS|js/modernizr-2.6.2-respond-1.1.0.min.js FXUS|js/jquery-1.10.2.min.js FXUS|js/jquery-ui.js FXUS|layerslider/jQuery/jquery-easing-1.3.js FXUS|layerslider/jQuery/jquery-transit-modified.js FXUS|layerslider/js/layerslider.transitions.js FXUS|layerslider/js/layerslider.kreaturamedia.jquery.js NXHS|http://ajax.googleapis.com/ajax/libs/jquery/x.x.x/jquery.min.js NXUS|css/font-awesome-ie7.min.css NHSS|https://www.facebook.com/pages/Access-To-A-Better-Tomorrow/7574851076461966 FKUS|thank_you.php FSUS|img/logo.png FSUS|img/logo.png FHUS|resources.html FSUS|icon_1.png FHUS|resources.html FSUS|icon_2.png FHUS|resources.html FSUS|icon_3.png FHUS|resources.html FSUS|icon_4.png FHUS|resources.html FSUS|icon_5.png FHUS|resources.html FSUS|icon_6.png FHUS|resources.html FSUS|icon_7.png FHUS|index.html FHUS|about.html FHUS|resources.html FHUS|events.html FHUS|news.html FHUS|donate.html FHUS|contactus.html NHUS|mailto:justinp@a-bt.org NHSS|https://www.facebook.com/pages/Access-To-A-Better-Tomorrow/7574851076461966 FSUS|img/s6.png FSUS|img/s4.png FSUS|img/s1.png FSUS|img/s2.png FSUS|img/s3.png FSUS|img/s5.png FSUS|img/s7.png FSUS|img/s8.png FSUS|img/s9.png FSUS|img/s10.png FSUS|img/s11.png FSUS|img/s12.png FSUS|img/s13.png FSUS|img/s14.png FSUS|img/s15.png FSUS|img/s16.png NASS|https://www.paypal.com/cgi-bin/webscr NHSS|https://www.gagivesday.org/c/GGD/Search NSSS|https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif NSSS|https://www.paypalobjects.com/en_US/i/scr/pixel.gif NHSS|https://www.facebook.com/pages/Access-To-A-Better-Tomorrow/7574851076461966 FSUS|js/jquery.queryloader2.js FSUS|js/bootstrap.min.js FSUS|js/twitter-bootstrap-hover-dropdown.min.js FSUS|js/jquery.carouFredSel-6.2.1.js FSUS|js/jquery.touchSwipe.min.js FSUS|js/jquery.prettyPhoto.js FSUS|js/jquery.flexslider-min.js FSUS|js/waypoints.min.js FSUS|js/jquery.stellar.min.js FSUS|js/masonry.pkgd.min.js FSUS|js/SmoothScroll.js FSUS|js/main.js FSUS|js/styleswitcher.js
vti_cachedneedsrewrite:BR|false
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_charset:SR|utf-8
vti_backlinkinfo:VX|thank_you.php
